#!/usr/bin/env bash

# To access environment variables
source "$HOME/dotfiles/zsh/.zshenv"

for dir in "$DOTFILES"/*/; do
	dir=${dir%/}
	rm -rf "$XDG_CONFIG_HOME/${dir##*/}"
	ln -s "$dir" "$XDG_CONFIG_HOME"
done

# Exceptions
ln -sf "$DOTFILES/zsh/.zshenv" "$HOME"
ln -sf "$DOTFILES/.editorconfig" "$HOME"

# Requirements
mkdir -p "$XDG_DATA_HOME/tmux/plugins"
mkdir -p "$XDG_CACHE_HOME/zsh"
mkdir -p "$XDG_DATA_HOME/vim"
