#!/usr/bin/env zsh

# To access environment variables
source "$HOME/dotfiles/zsh/.zshenv"

for dir in "$DOTFILES"/*/; do
	[[ $dir = "$DOTFILES/scripts/" ]] && continue
	dir=${dir%/}
	rm -rf "$XDG_CONFIG_HOME/${dir##*/}"
	ln -s "$dir" "$XDG_CONFIG_HOME"
done

# Requirements
mkdir -p "$XDG_DATA_HOME/tmux/plugins"
mkdir -p "$XDG_CACHE_HOME/zsh"
mkdir -p "$XDG_DATA_HOME/zsh"
mkdir -p "$XDG_DATA_HOME/vim"
mkdir -p "$USER_SCRIPTS"

# Exceptions
ln -sf "$DOTFILES/.editorconfig" "$HOME"
ln -sf "$ZDOTDIR/.zshenv" "$HOME"

rm -rf "$XDG_DATA_HOME/zsh/functions"
ln -s "$ZDOTDIR/functions" "$XDG_DATA_HOME/zsh"

rm -rf "$USER_SCRIPTS"
ln -s "$DOTFILES/scripts" "$USER_SCRIPTS"
