#!/usr/bin/env zsh

# WARN: Some zshisms here won't work in bash.

function focus_fmenu { i3-msg --quiet '[title="fmenu"] focus' }

focus_fmenu && exit 0
xdotool search --name fmenu && exit 1

typeset fzf_cmd='fzf --ghost="Enter an application name"'

urxvt -title 'fmenu' -e i3-dmenu-desktop --dmenu="zsh -i -c '$fzf_cmd'" &|

# Attempt to focus newly created window
repeat 5; do
	focus_fmenu && exit 0
	sleep 0.2
done

